"""add cash_balance to portfolios

Revision ID: b210b759b9e7
Revises: 5547a8a30599
Create Date: 2026-03-16 11:44:43.186926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b210b759b9e7'
down_revision: Union[str, Sequence[str], None] = '5547a8a30599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('cash_balance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'cash_balance')
    # ### end Alembic commands ###
